### ISSUE TITLE
路线管理中管理出发时间和截止时间的修改

### ISSUE THREAD

**Issue by litian1218** [yunzhiclub/tour#213]
1.时间的字段类型均改为时间戳
2.数据表为以下修改
出发时间-起：begin_time  int
出发时间-止：end_time int
到期时间：deadline int
3.修改对应的保存方法

**Comment by litian1218** [comment]
@chuhang123

**Comment by chuhang123** [comment]
为什么要改成int类型呢，是前台取数据有问题么？

**Comment by litian1218** [comment]
对，你这个存储方式会导致调用出发时间截止时间的所有方法都转换一下格式，你直接存的时候存int就行了，后台显示转换一下

**Comment by chuhang123** [comment]
如果是时间戳的话存取都要转换格式，date类型就不用转换格式了，取出来j就能直接用，如xxxx-xx-xx

**Comment by litian1218** [comment]
js中调用时间的时候都是时间戳格式，你这样就是光自己存取的时候方便了，前台用的时候你还是要转换成时间戳

**Comment by chuhang123** [comment]
恩恩，好的，我等下改，我是先新建个分支，写完之后pull到development分支，然后删除分支么？

**Comment by litian1218** [comment]
嗯，分支名字就是任务名字

**Comment by chuhang123** [comment]
好的

**Comment by litian1218** [comment]
功能写完记得关闭issue

**Comment by chuhang123** [comment]
好的
